export function getRandomWord() {
  const spanishWords = [
    'hola',
    'adios',
    'gracias',
    'por favor',
    'perro',
    'gato',
    'casa',
    'carro',
    'computadora',
    'telefono',
    'escuela',
    'trabajo',
    'comida',
    'agua',
    'cerveza',
    'vino',
    'leche',
    'pan',
    'queso',
    'jamon',
    'pescado',
    'pollo',
    'res',
    'cerdo',
    'verduras',
    'frutas',
    'arroz',
    'frijoles',
    'tortilla',
    'salsa',
    'chile',
    'sal',
    'pimienta',
    'azucar',
    'aceite',
    'mantequilla',
    'huevo',
  ];
  const randomIndex = Math.floor(Math.random() * spanishWords.length);
  return spanishWords[randomIndex].toUpperCase();
}
